//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGINHISTORY
    {
        public decimal ID { get; set; }
        public decimal USERID { get; set; }
        public string IPADDRESS { get; set; }
        public Nullable<System.DateTime> LOGINTIME { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string OTPCODE { get; set; }
        public Nullable<System.DateTime> OTPEXPIRE { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
