//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_PHONGGYMEntities : DbContext
    {
        public QL_PHONGGYMEntities()
 : base("name=QL_PHONGGYMEntities")
        {
        }

        public QL_PHONGGYMEntities(bool userAdmin)
            : base("name=ADMIN_ENTITY")
        {
        }

        public QL_PHONGGYMEntities(string connStr)
           : base(connStr)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHECKIN> CHECKINs { get; set; }
        public virtual DbSet<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CHUYENMON> CHUYENMONs { get; set; }
        public virtual DbSet<DANGKYGOITAP> DANGKYGOITAPs { get; set; }
        public virtual DbSet<DANGKYLOP> DANGKYLOPs { get; set; }
        public virtual DbSet<DANGKYPT> DANGKYPTs { get; set; }
        public virtual DbSet<DIACHI> DIACHIs { get; set; }
        public virtual DbSet<GOITAP> GOITAPs { get; set; }
        public virtual DbSet<HINHANH> HINHANHs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LICHLOP> LICHLOPs { get; set; }
        public virtual DbSet<LICHTAPPT> LICHTAPPTs { get; set; }
        public virtual DbSet<LOAIKHACHHANG> LOAIKHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<LOGINHISTORY> LOGINHISTORies { get; set; }
        public virtual DbSet<LOPHOC> LOPHOCs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
    
        public virtual int GET_ORACLE_USERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ORACLE_USERS");
        }
    
        public virtual int GET_RECENT_AUDIT_LOGS(string p_OWNER, Nullable<decimal> p_HOURS)
        {
            var p_OWNERParameter = p_OWNER != null ?
                new ObjectParameter("P_OWNER", p_OWNER) :
                new ObjectParameter("P_OWNER", typeof(string));
    
            var p_HOURSParameter = p_HOURS.HasValue ?
                new ObjectParameter("P_HOURS", p_HOURS) :
                new ObjectParameter("P_HOURS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_RECENT_AUDIT_LOGS", p_OWNERParameter, p_HOURSParameter);
        }
    
        public virtual int GET_USER_SESSIONS(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_USER_SESSIONS", p_USERNAMEParameter);
        }
    
        public virtual int KILL_USER_SESSION(Nullable<decimal> p_SID, Nullable<decimal> p_SERIAL)
        {
            var p_SIDParameter = p_SID.HasValue ?
                new ObjectParameter("P_SID", p_SID) :
                new ObjectParameter("P_SID", typeof(decimal));
    
            var p_SERIALParameter = p_SERIAL.HasValue ?
                new ObjectParameter("P_SERIAL", p_SERIAL) :
                new ObjectParameter("P_SERIAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("KILL_USER_SESSION", p_SIDParameter, p_SERIALParameter);
        }
    
        public virtual int P_DECRYPTADDCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DECRYPTADDCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_DECRYPTMULCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DECRYPTMULCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_ENCRYPTADDCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_ENCRYPTADDCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int P_ENCRYPTMULCIPHER(string sTR, Nullable<decimal> k, ObjectParameter rESULT)
        {
            var sTRParameter = sTR != null ?
                new ObjectParameter("STR", sTR) :
                new ObjectParameter("STR", typeof(string));
    
            var kParameter = k.HasValue ?
                new ObjectParameter("K", k) :
                new ObjectParameter("K", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_ENCRYPTMULCIPHER", sTRParameter, kParameter, rESULT);
        }
    
        public virtual int SP_CHECKCHINE(string p_USERNAME, ObjectParameter p_RESULT)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECKCHINE", p_USERNAMEParameter, p_RESULT);
        }
    
        public virtual int SP_CHECK_OTHER_MACHINE(ObjectParameter p_RESULT)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_OTHER_MACHINE", p_RESULT);
        }
    
        public virtual int SP_CHECK_OWN_SESSION(ObjectParameter p_SID, ObjectParameter p_SERIAL)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_OWN_SESSION", p_SID, p_SERIAL);
        }
    
        public virtual int SP_CHECK_SESSION_FULL(string p_USERNAME, Nullable<decimal> p_SID, Nullable<decimal> p_SERIAL, Nullable<decimal> p_MAX_IDLE_SEC, ObjectParameter p_STATUS_CODE, ObjectParameter p_MESSAGE)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_SIDParameter = p_SID.HasValue ?
                new ObjectParameter("P_SID", p_SID) :
                new ObjectParameter("P_SID", typeof(decimal));
    
            var p_SERIALParameter = p_SERIAL.HasValue ?
                new ObjectParameter("P_SERIAL", p_SERIAL) :
                new ObjectParameter("P_SERIAL", typeof(decimal));
    
            var p_MAX_IDLE_SECParameter = p_MAX_IDLE_SEC.HasValue ?
                new ObjectParameter("P_MAX_IDLE_SEC", p_MAX_IDLE_SEC) :
                new ObjectParameter("P_MAX_IDLE_SEC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_SESSION_FULL", p_USERNAMEParameter, p_SIDParameter, p_SERIALParameter, p_MAX_IDLE_SECParameter, p_STATUS_CODE, p_MESSAGE);
        }
    
        public virtual int SP_CHECK_SESSION_STATUS(string p_USERNAME, Nullable<decimal> p_SID, Nullable<decimal> p_SERIAL, Nullable<decimal> p_MAX_IDLE_SEC, ObjectParameter p_STATUS_MSG)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_SIDParameter = p_SID.HasValue ?
                new ObjectParameter("P_SID", p_SID) :
                new ObjectParameter("P_SID", typeof(decimal));
    
            var p_SERIALParameter = p_SERIAL.HasValue ?
                new ObjectParameter("P_SERIAL", p_SERIAL) :
                new ObjectParameter("P_SERIAL", typeof(decimal));
    
            var p_MAX_IDLE_SECParameter = p_MAX_IDLE_SEC.HasValue ?
                new ObjectParameter("P_MAX_IDLE_SEC", p_MAX_IDLE_SEC) :
                new ObjectParameter("P_MAX_IDLE_SEC", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_SESSION_STATUS", p_USERNAMEParameter, p_SIDParameter, p_SERIALParameter, p_MAX_IDLE_SECParameter, p_STATUS_MSG);
        }
    
        public virtual int SP_CHECK_USER_SESSION(string p_USERNAME, Nullable<decimal> p_SID, Nullable<decimal> p_SERIAL, ObjectParameter p_STATUS)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_SIDParameter = p_SID.HasValue ?
                new ObjectParameter("P_SID", p_SID) :
                new ObjectParameter("P_SID", typeof(decimal));
    
            var p_SERIALParameter = p_SERIAL.HasValue ?
                new ObjectParameter("P_SERIAL", p_SERIAL) :
                new ObjectParameter("P_SERIAL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHECK_USER_SESSION", p_USERNAMEParameter, p_SIDParameter, p_SERIALParameter, p_STATUS);
        }
    
        public virtual int SP_CREATE_MANAGER_USER(string p_USERNAME, string p_PASSWORD)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_MANAGER_USER", p_USERNAMEParameter, p_PASSWORDParameter);
        }
    
        public virtual int SP_CREATE_ROLE(string p_ROLE_NAME)
        {
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_ROLE", p_ROLE_NAMEParameter);
        }
    
        public virtual int SP_DANGKYTAPTHU(string p_TENKH, string p_SDT, string p_EMAIL)
        {
            var p_TENKHParameter = p_TENKH != null ?
                new ObjectParameter("P_TENKH", p_TENKH) :
                new ObjectParameter("P_TENKH", typeof(string));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DANGKYTAPTHU", p_TENKHParameter, p_SDTParameter, p_EMAILParameter);
        }
    
        public virtual int SP_DROP_USER(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DROP_USER", p_USERNAMEParameter);
        }
    
        public virtual int SP_GET_AUDITED_TABLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_AUDITED_TABLES");
        }
    
        public virtual int SP_GET_AUDIT_LOGS(string p_USERNAME, string p_TABLE_NAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_TABLE_NAMEParameter = p_TABLE_NAME != null ?
                new ObjectParameter("P_TABLE_NAME", p_TABLE_NAME) :
                new ObjectParameter("P_TABLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_AUDIT_LOGS", p_USERNAMEParameter, p_TABLE_NAMEParameter);
        }
    
        public virtual int SP_GET_EXISTING_PRIVS(string p_TARGET, string p_TABLE_NAME)
        {
            var p_TARGETParameter = p_TARGET != null ?
                new ObjectParameter("P_TARGET", p_TARGET) :
                new ObjectParameter("P_TARGET", typeof(string));
    
            var p_TABLE_NAMEParameter = p_TABLE_NAME != null ?
                new ObjectParameter("P_TABLE_NAME", p_TABLE_NAME) :
                new ObjectParameter("P_TABLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_EXISTING_PRIVS", p_TARGETParameter, p_TABLE_NAMEParameter);
        }
    
        public virtual int SP_GET_METADATA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_METADATA");
        }
    
        public virtual int SP_GET_USERS_IN_ROLE(string p_ROLE_NAME)
        {
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GET_USERS_IN_ROLE", p_ROLE_NAMEParameter);
        }
    
        public virtual int SP_GRANT_PERMISSION(string p_USER_OR_ROLE, string p_TABLE_NAME, string p_PRIVILEGE)
        {
            var p_USER_OR_ROLEParameter = p_USER_OR_ROLE != null ?
                new ObjectParameter("P_USER_OR_ROLE", p_USER_OR_ROLE) :
                new ObjectParameter("P_USER_OR_ROLE", typeof(string));
    
            var p_TABLE_NAMEParameter = p_TABLE_NAME != null ?
                new ObjectParameter("P_TABLE_NAME", p_TABLE_NAME) :
                new ObjectParameter("P_TABLE_NAME", typeof(string));
    
            var p_PRIVILEGEParameter = p_PRIVILEGE != null ?
                new ObjectParameter("P_PRIVILEGE", p_PRIVILEGE) :
                new ObjectParameter("P_PRIVILEGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GRANT_PERMISSION", p_USER_OR_ROLEParameter, p_TABLE_NAMEParameter, p_PRIVILEGEParameter);
        }
    
        public virtual int SP_GRANT_ROLE_TO_USER(string p_USER_NAME, string p_ROLE_NAME)
        {
            var p_USER_NAMEParameter = p_USER_NAME != null ?
                new ObjectParameter("P_USER_NAME", p_USER_NAME) :
                new ObjectParameter("P_USER_NAME", typeof(string));
    
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GRANT_ROLE_TO_USER", p_USER_NAMEParameter, p_ROLE_NAMEParameter);
        }
    
        public virtual int SP_KHACHHANGDANGKY(string p_TENKH, string p_GIOITINH, Nullable<System.DateTime> p_NGAYSINH, string p_SDT, string p_EMAIL, string p_TENDANGNHAP, string p_MATKHAU)
        {
            var p_TENKHParameter = p_TENKH != null ?
                new ObjectParameter("P_TENKH", p_TENKH) :
                new ObjectParameter("P_TENKH", typeof(string));
    
            var p_GIOITINHParameter = p_GIOITINH != null ?
                new ObjectParameter("P_GIOITINH", p_GIOITINH) :
                new ObjectParameter("P_GIOITINH", typeof(string));
    
            var p_NGAYSINHParameter = p_NGAYSINH.HasValue ?
                new ObjectParameter("P_NGAYSINH", p_NGAYSINH) :
                new ObjectParameter("P_NGAYSINH", typeof(System.DateTime));
    
            var p_SDTParameter = p_SDT != null ?
                new ObjectParameter("P_SDT", p_SDT) :
                new ObjectParameter("P_SDT", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_TENDANGNHAPParameter = p_TENDANGNHAP != null ?
                new ObjectParameter("P_TENDANGNHAP", p_TENDANGNHAP) :
                new ObjectParameter("P_TENDANGNHAP", typeof(string));
    
            var p_MATKHAUParameter = p_MATKHAU != null ?
                new ObjectParameter("P_MATKHAU", p_MATKHAU) :
                new ObjectParameter("P_MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACHHANGDANGKY", p_TENKHParameter, p_GIOITINHParameter, p_NGAYSINHParameter, p_SDTParameter, p_EMAILParameter, p_TENDANGNHAPParameter, p_MATKHAUParameter);
        }
    
        public virtual int SP_KHACHHANGLOGIN(string p_TENDANGNHAP, string p_MATKHAU)
        {
            var p_TENDANGNHAPParameter = p_TENDANGNHAP != null ?
                new ObjectParameter("P_TENDANGNHAP", p_TENDANGNHAP) :
                new ObjectParameter("P_TENDANGNHAP", typeof(string));
    
            var p_MATKHAUParameter = p_MATKHAU != null ?
                new ObjectParameter("P_MATKHAU", p_MATKHAU) :
                new ObjectParameter("P_MATKHAU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACHHANGLOGIN", p_TENDANGNHAPParameter, p_MATKHAUParameter);
        }
    
        public virtual int SP_KHOIPHUCMATKHAU(string p_EMAIL, string p_MATKHAUMOI)
        {
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_MATKHAUMOIParameter = p_MATKHAUMOI != null ?
                new ObjectParameter("P_MATKHAUMOI", p_MATKHAUMOI) :
                new ObjectParameter("P_MATKHAUMOI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHOIPHUCMATKHAU", p_EMAILParameter, p_MATKHAUMOIParameter);
        }
    
        public virtual int SP_LAYCHITIETHOADON(Nullable<decimal> p_MAHD)
        {
            var p_MAHDParameter = p_MAHD.HasValue ?
                new ObjectParameter("P_MAHD", p_MAHD) :
                new ObjectParameter("P_MAHD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LAYCHITIETHOADON", p_MAHDParameter);
        }
    
        public virtual int SP_LOCK_USER(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOCK_USER", p_USERNAMEParameter);
        }
    
        public virtual int SP_LOGOUT_USER(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LOGOUT_USER", p_USERNAMEParameter);
        }
    
        public virtual int SP_MANAGE_SESSIONS(string p_USERNAME, Nullable<decimal> p_MAX_SESSIONS)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            var p_MAX_SESSIONSParameter = p_MAX_SESSIONS.HasValue ?
                new ObjectParameter("P_MAX_SESSIONS", p_MAX_SESSIONS) :
                new ObjectParameter("P_MAX_SESSIONS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MANAGE_SESSIONS", p_USERNAMEParameter, p_MAX_SESSIONSParameter);
        }
    
        public virtual int SP_RESOLVE_LOGIN_LIMIT(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RESOLVE_LOGIN_LIMIT", p_USERNAMEParameter);
        }
    
        public virtual int SP_REVOKE_PERMISSION(string p_USER_OR_ROLE, string p_TABLE_NAME, string p_PRIVILEGE)
        {
            var p_USER_OR_ROLEParameter = p_USER_OR_ROLE != null ?
                new ObjectParameter("P_USER_OR_ROLE", p_USER_OR_ROLE) :
                new ObjectParameter("P_USER_OR_ROLE", typeof(string));
    
            var p_TABLE_NAMEParameter = p_TABLE_NAME != null ?
                new ObjectParameter("P_TABLE_NAME", p_TABLE_NAME) :
                new ObjectParameter("P_TABLE_NAME", typeof(string));
    
            var p_PRIVILEGEParameter = p_PRIVILEGE != null ?
                new ObjectParameter("P_PRIVILEGE", p_PRIVILEGE) :
                new ObjectParameter("P_PRIVILEGE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REVOKE_PERMISSION", p_USER_OR_ROLEParameter, p_TABLE_NAMEParameter, p_PRIVILEGEParameter);
        }
    
        public virtual int SP_REVOKE_ROLE_FROM_USER(string p_USER_NAME, string p_ROLE_NAME)
        {
            var p_USER_NAMEParameter = p_USER_NAME != null ?
                new ObjectParameter("P_USER_NAME", p_USER_NAME) :
                new ObjectParameter("P_USER_NAME", typeof(string));
    
            var p_ROLE_NAMEParameter = p_ROLE_NAME != null ?
                new ObjectParameter("P_ROLE_NAME", p_ROLE_NAME) :
                new ObjectParameter("P_ROLE_NAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_REVOKE_ROLE_FROM_USER", p_USER_NAMEParameter, p_ROLE_NAMEParameter);
        }
    
        public virtual int SP_TEST_CONNECTION(ObjectParameter p_ALIVE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TEST_CONNECTION", p_ALIVE);
        }
    
        public virtual int SP_UNLOCK_USER(string p_USERNAME)
        {
            var p_USERNAMEParameter = p_USERNAME != null ?
                new ObjectParameter("P_USERNAME", p_USERNAME) :
                new ObjectParameter("P_USERNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UNLOCK_USER", p_USERNAMEParameter);
        }
    }
}
