//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_SESSIONS
    {
        public string SESSION_ID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<System.DateTime> CREATED_AT { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
    }
}
